version: '3'
services:
  db:
    image: contemporanica/bbdd:Definitivo
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ContemporanicaDaw2@23
      MYSQL_DATABASE: contemporanica
      MYSQL_USER: contemporanica
      MYSQL_PASSWORD: ContemporanicaDaw2@23
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  api:
    image: contemporanica/api:latest
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: contemporanica
      DB_PASSWORD: ContemporanicaDaw2@23
      DB_PORT: "3307"
      TOKEN: a944114ba4149684eb4e6b00e6093fdb
volumes:
  db_data: